version: "3.1"
services:

  project-db:
    image: mariadb:10.4
    container_name: project-db
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
    ports:
      - "4004:3306"

  webserver:
    image: nginx:alpine
    container_name: nginx
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - project-db

  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm
    working_dir: /application
    volumes:
      - ./Server:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  appserver:
    image: project-angular
    container_name: project-angular
    ports:
      - "3003:81"